FROM golang:1.14 as builder

ARG ARCH=amd64
ARG GOPATH="/go"
ARG GO111MODULE=on

WORKDIR $GOPATH/src/github.com/omc-college/management-system/

COPY go.mod go.sum ./
COPY pkg ./pkg
COPY cmd/rbac ./cmd/rbac

RUN go get -d -v ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${ARCH} \
    go build -o $GOPATH/bin/rbac -a ./cmd/rbac

FROM scratch

EXPOSE 8000

COPY --from=builder /go/bin/rbac /bin/rbac

ENTRYPOINT ["/bin/rbac"]