FROM golang:1.14

EXPOSE 8000

WORKDIR /go/src/app
COPY ./go.mod ./go.sum ./
COPY ./pkg ./pkg
COPY ./cmd/rbacgen ./cmd/rbacgen
COPY ./api ./api

RUN go get -d -v ./...
RUN go install -v ./...

CMD rbacgen --create \
 && rbacgen --fill