BEGIN;

DROP TABLE IF EXISTS endpoints CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS roles_to_features CASCADE;
DROP TABLE IF EXISTS features_to_endpoints CASCADE;

COMMIT;