dbconnection:
  user: 'postgres'
  password: 'superuser'
  host: 'rbac-db'
  port: '5432'
  database: 'roles'
  sslmode: 'disable'

mqconnection:
  host: 'nats-streaming'
  port: '4222'

pubsub:
  clusterid: 'test-cluster'
  clientid: 'client-rbacgen-id'
  queuename: 'new-queue'
  pingsinterval: 20
  maxunsuccessfulpings: 5
  
rbacgen:
  specsPaths: 
    - '/etc/rbacgen/api/ims/ims-api.yaml'
    - '/etc/rbacgen/api/rbac/rbac-api.yaml'
    - '/etc/rbacgen/api/timetable/timetable-api.yaml'
  tmplPath: '/etc/rbacgen/roleTmpl.yaml'
