webapi_address: ':8080'
dbconnection:
  user: 'postgres'
  password: '2701'
  host: 'localhost'
  port: '5432'
  database: 'postgres'
  sslmode: 'disable'
siningkey: 'signingKey12345678900987654321'
expirationtime: 24h